-- MySQL Script generated by MySQL Workbench
-- 09/21/16 13:29:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema codiga
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codiga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codiga` DEFAULT CHARACTER SET latin1 ;
USE `codiga` ;

-- -----------------------------------------------------
-- Table `codiga`.`tipo_de_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`tipo_de_usuario` (
  `id_tipo_de_usuario` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'NULL - Normal\n1 - Super usuario (root)\n2 - Soporte (Administrador)',
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_de_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(45) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `telefono` INT(10) UNSIGNED NULL DEFAULT NULL,
  `celular` INT(10) UNSIGNED NULL DEFAULT NULL,
  `callenumero` VARCHAR(45) NULL DEFAULT NULL,
  `colonia` VARCHAR(45) NULL DEFAULT NULL,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_paga` DATETIME NULL DEFAULT NULL,
  `fecha_paga_prox` DATETIME NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `tipo_de_usuario_id_tipo_de_usuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_tipo_de_usuario1_idx` (`tipo_de_usuario_id_tipo_de_usuario` ASC),
  CONSTRAINT `fk_usuario_tipo_de_usuario1`
    FOREIGN KEY (`tipo_de_usuario_id_tipo_de_usuario`)
    REFERENCES `codiga`.`tipo_de_usuario` (`id_tipo_de_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`cabeza_ganado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`cabeza_ganado` (
  `id_cabeza` INT(11) NOT NULL AUTO_INCREMENT,
  `procedencia` TINYINT(1) NOT NULL COMMENT '1 si es nacido y 0 si es comprado',
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(10) NULL DEFAULT NULL,
  `raza` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `des_procedencia` VARCHAR(45) NULL DEFAULT NULL,
  `madre` VARCHAR(45) NULL DEFAULT NULL,
  `padre` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_destino` DATE NULL DEFAULT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  `raza_padre` VARCHAR(45) NULL DEFAULT NULL,
  `raza_madre` VARCHAR(45) NULL DEFAULT NULL,
  `codigo_padre` INT(11) NULL DEFAULT NULL,
  `codigo_madre` INT(11) NULL DEFAULT NULL,
  `usuario_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_cabeza`, `usuario_id_usuario`),
  INDEX `fk_cabeza_ganado_usuario_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_cabeza_ganado_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `codiga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`comprador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`comprador` (
  `id_comprador` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `usuario_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_comprador`, `usuario_id_usuario`),
  INDEX `fk_comprador_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_comprador_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `codiga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`ctrl_errores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`ctrl_errores` (
  `id_errores` INT(11) NOT NULL AUTO_INCREMENT COMMENT '0 - Dispositivo\n1 - Pagina Web\n2 - Android\n3 - iOS',
  `nombre_error` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_errores`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`ctrl_reproductivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`ctrl_reproductivo` (
  `id_ctrl_reproductivo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_toro` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_secado` DATE NULL DEFAULT NULL,
  `fecha_parto` DATE NULL DEFAULT NULL,
  `num_nacidos` INT(11) NULL DEFAULT NULL,
  `num_muertos` INT(11) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Inseminación o Monta',
  `cabeza_ganado_id_cabeza` INT(11) NOT NULL,
  PRIMARY KEY (`id_ctrl_reproductivo`, `cabeza_ganado_id_cabeza`),
  INDEX `fk_ctrl_reproductivo_cabeza_ganado1_idx` (`cabeza_ganado_id_cabeza` ASC),
  CONSTRAINT `fk_ctrl_reproductivo_cabeza_ganado1`
    FOREIGN KEY (`cabeza_ganado_id_cabeza`)
    REFERENCES `codiga`.`cabeza_ganado` (`id_cabeza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`vacunas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`vacunas` (
  `id_vacunas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `usuario_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_vacunas`, `usuario_id_usuario`),
  INDEX `fk_vacunas_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_vacunas_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `codiga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`ctrl_vacunas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`ctrl_vacunas` (
  `id_ctrl_vacunas` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_prox` DATE NULL DEFAULT NULL,
  `costo` INT(11) NULL DEFAULT NULL,
  `cabeza_ganado_id_cabeza` INT(11) NOT NULL,
  `vacunas_id_vacunas` INT(11) NOT NULL,
  PRIMARY KEY (`id_ctrl_vacunas`, `cabeza_ganado_id_cabeza`, `vacunas_id_vacunas`),
  INDEX `fk_ctrl_vacunas_cabeza_ganado1_idx` (`cabeza_ganado_id_cabeza` ASC),
  INDEX `fk_ctrl_vacunas_vacunas1_idx` (`vacunas_id_vacunas` ASC),
  CONSTRAINT `fk_ctrl_vacunas_cabeza_ganado1`
    FOREIGN KEY (`cabeza_ganado_id_cabeza`)
    REFERENCES `codiga`.`cabeza_ganado` (`id_cabeza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ctrl_vacunas_vacunas1`
    FOREIGN KEY (`vacunas_id_vacunas`)
    REFERENCES `codiga`.`vacunas` (`id_vacunas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`destino` (
  `id_destino` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_final` VARCHAR(45) NOT NULL,
  `costo` VARCHAR(45) NULL DEFAULT NULL,
  `cabeza_ganado_id_cabeza` INT(11) NOT NULL,
  PRIMARY KEY (`id_destino`, `cabeza_ganado_id_cabeza`),
  INDEX `fk_destino_cabeza_ganado1_idx` (`cabeza_ganado_id_cabeza` ASC),
  CONSTRAINT `fk_destino_cabeza_ganado1`
    FOREIGN KEY (`cabeza_ganado_id_cabeza`)
    REFERENCES `codiga`.`cabeza_ganado` (`id_cabeza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`dispositivo` (
  `id_dispositivo` INT(11) NOT NULL,
  `identificador` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL COMMENT '0 No se esta usado, 1 se esta usado',
  `cabeza_ganado_id_cabeza` INT(11) NOT NULL,
  PRIMARY KEY (`id_dispositivo`, `cabeza_ganado_id_cabeza`),
  INDEX `fk_dispositivo_cabeza_ganado1_idx` (`cabeza_ganado_id_cabeza` ASC),
  CONSTRAINT `fk_dispositivo_cabeza_ganado1`
    FOREIGN KEY (`cabeza_ganado_id_cabeza`)
    REFERENCES `codiga`.`cabeza_ganado` (`id_cabeza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`factura` (
  `id_factura` INT(11) NOT NULL AUTO_INCREMENT,
  `num_factura` VARCHAR(45) NOT NULL,
  `costo` INT(11) NOT NULL,
  `comprador_id_comprador` INT(11) NOT NULL,
  PRIMARY KEY (`id_factura`, `comprador_id_comprador`),
  INDEX `fk_factura_comprador1_idx` (`comprador_id_comprador` ASC),
  CONSTRAINT `fk_factura_comprador1`
    FOREIGN KEY (`comprador_id_comprador`)
    REFERENCES `codiga`.`comprador` (`id_comprador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`geo_limite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`geo_limite` (
  `id_limite` INT(11) NOT NULL AUTO_INCREMENT,
  `latitud` DECIMAL(18,15) NOT NULL,
  `longitud` DECIMAL(18,15) NOT NULL,
  `usuario_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_limite`, `usuario_id_usuario`),
  INDEX `fk_geo_limite_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_geo_limite_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `codiga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`geo_posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`geo_posicion` (
  `id_geo_posicion` INT(11) NOT NULL,
  `lat` DECIMAL(18,15) NOT NULL COMMENT 'Latitud de la vaca',
  `lng` DECIMAL(18,15) NOT NULL COMMENT 'Longitud de la vaca',
  `temp` FLOAT NULL DEFAULT NULL COMMENT 'temperatura de la vaca\n',
  `accel` INT(11) NULL DEFAULT NULL COMMENT 'Movimiento total de la vaca',
  `bat_level` INT(11) NULL DEFAULT NULL COMMENT 'Nivel de la bateria',
  `bat_temp` INT(11) NULL DEFAULT NULL,
  `status` SET('0', '1') NULL DEFAULT NULL COMMENT '0 - Local\n1 - Nube',
  `celo` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_hora` DATETIME NULL DEFAULT NULL,
  `cabeza_ganado_usuario_id_usuario` INT(11) NOT NULL,
  `dispositivo_id_dispositivo` INT(11) NOT NULL,
  `cabeza_ganado_usuario_id_usuario1` INT(11) NOT NULL,
  PRIMARY KEY (`id_geo_posicion`, `cabeza_ganado_usuario_id_usuario`, `dispositivo_id_dispositivo`, `cabeza_ganado_usuario_id_usuario1`),
  INDEX `fk_geo_posicion_cabeza_ganado1_idx` (`cabeza_ganado_usuario_id_usuario` ASC),
  INDEX `fk_geo_posicion_dispositivo1_idx` (`dispositivo_id_dispositivo` ASC),
  INDEX `fk_geo_posicion_cabeza_ganado1_idx1` (`cabeza_ganado_usuario_id_usuario1` ASC),
  CONSTRAINT `fk_geo_posicion_dispositivo1`
    FOREIGN KEY (`dispositivo_id_dispositivo`)
    REFERENCES `codiga`.`dispositivo` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_geo_posicion_cabeza_ganado1`
    FOREIGN KEY (`cabeza_ganado_usuario_id_usuario1`)
    REFERENCES `codiga`.`cabeza_ganado` (`usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`produccion` (
  `id_produccion` INT(11) NOT NULL AUTO_INCREMENT,
  `litros` INT(11) NOT NULL,
  `vendida` INT(11) NOT NULL,
  `comprandor` VARCHAR(45) NULL DEFAULT NULL,
  `cabeza_ganado_id_cabeza` INT(11) NOT NULL,
  PRIMARY KEY (`id_produccion`, `cabeza_ganado_id_cabeza`),
  INDEX `fk_produccion_cabeza_ganado1_idx` (`cabeza_ganado_id_cabeza` ASC),
  CONSTRAINT `fk_produccion_cabeza_ganado1`
    FOREIGN KEY (`cabeza_ganado_id_cabeza`)
    REFERENCES `codiga`.`cabeza_ganado` (`id_cabeza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `codiga`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codiga`.`ticket` (
  `id_ticket` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(90) NULL DEFAULT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `estado_tickets` VARCHAR(15) NOT NULL,
  `fecha_fin` DATETIME NULL,
  `usuario_id_usuario` INT(11) NOT NULL,
  `ctrl_errores_id_errores` INT(11) NOT NULL,
  PRIMARY KEY (`id_ticket`, `usuario_id_usuario`, `ctrl_errores_id_errores`),
  INDEX `fk_ticket_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_ticket_ctrl_errores1_idx` (`ctrl_errores_id_errores` ASC),
  CONSTRAINT `fk_ticket_ctrl_errores1`
    FOREIGN KEY (`ctrl_errores_id_errores`)
    REFERENCES `codiga`.`ctrl_errores` (`id_errores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `codiga`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
